[build]
  publish = "_site"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'"
    Referrer-Policy = "strict-origin"
    X-Content-Type-Options = "nosniff"